### ISSUE TITLE
Difference between arxiv paper v1 and the camera ready version?

### ISSUE THREAD

**Issue by yucornetto** [ZwwWayne/K-Net#4]
Hi, thanks so much for sharing the great work and congrats on the paper acceptance!

I saw that in the arxiv v1 version of the paper, it reports a PQ score = 52.1 PQ of K-Net with Swin-L backbone. In the camera ready version, the score is improved to 55.2 PQ with the same architecture. I looked in to the paper but did not find out what is the difference. Besides, it seems that other results (e.g., instance segmentation) remain the same. May I ask what is the difference between arxiv v1 version and current one?

Thanks!

**Comment by ZwwWayne** [comment]
Hi @yucornetto ,
Thanks for your attention! After the paper release, we made some modifications of K-Net on panoptic segmentation from the original implementation as below:
1.  In the arxiv v1 version, we use similar annotations as Panoptic FPN, which uses instance segmentation annotations for thing segmentation and use masks generated from panoptic annotations for stuff segmentation. However, when we are implementing Panoptic FPN in [MMDet](https://github.com/open-mmlab/mmdetection), we find that using panoptic annotations for both things and stuff segmentation yields better results (~1 PQ better). This is because the occlusion is not well handled between masks in the instance segmentation annotations. Therefore, we change to only use panoptic annotation in the new K-Net based on the newest version of MMDetection. This improves ~1.4 PQ of K-Net.
2. We fixed a bug in inference. We find a class ID bug when pasting things and stuff masks in arxiv v1 and fixed it when we change to use the COCOPanopticDataset in the newest MMDetection. Simply fixing this issue could improve about 1.0 PQ.
3. We tried a new inference strategy. In arxiv v1 we paste masks of things and stuff separately following the same way as Panoptic FPN. In rebuttal, we tried a new strategy that pastes them in a mixed order based on their classification scores. It consistently improves K-Net by 0.3~0.4 PQ.
